/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javajavascript.demo.core.io;

public
class ASTCompilationUnit extends ASTNode {
  public ASTCompilationUnit(int id) {
    super(id);
  }

  public ASTCompilationUnit(JavadocParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=517ed386d2a5d5dd4186179e233085b4 (do not edit this line) */
