/* Generated By:JavaCC: Do not edit this line. JavadocParserTreeConstants.java Version 5.0 */
package org.javajavascript.demo.core.io;

public interface JavadocParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
  };
}
/* JavaCC - OriginalChecksum=a6200535e11a5c5203ebb5e8ca626032 (do not edit this line) */
