/* Generated By:JJTree&JavaCC: Do not edit this line. JavadocParserConstants.java */
package org.javajavascript.demo.core.io;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavadocParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINK_START = 1;
  /** RegularExpression Id. */
  int SEE_START = 2;
  /** RegularExpression Id. */
  int ANCHOR_START = 3;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int WS = 5;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int LINK = 7;
  /** RegularExpression Id. */
  int LINK_CLOSE = 8;
  /** RegularExpression Id. */
  int SEE = 9;
  /** RegularExpression Id. */
  int SEE_CLOSE = 10;
  /** RegularExpression Id. */
  int ANCHOR = 11;
  /** RegularExpression Id. */
  int ANCHOR_CLOSE = 12;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINK_START = 1;
  /** Lexical state. */
  int IN_SEE_START = 2;
  /** Lexical state. */
  int IN_ANCHOR_START = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LINK_START>",
    "<SEE_START>",
    "<ANCHOR_START>",
    "<SPACE>",
    "<WS>",
    "<COMMENT>",
    "<LINK>",
    "<LINK_CLOSE>",
    "<SEE>",
    "<SEE_CLOSE>",
    "<ANCHOR>",
    "<ANCHOR_CLOSE>",
  };

}
